name: .NET

on:
  push:
    tags:
    - "*.*.*"
    - "*.*.*-rc*"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Git Vars
      id: git_vars
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release external-task-extension -p:Version="${{ steps.git_vars.outputs.SOURCE_TAG }}"
    - name: Push to GitHub Packages
      run: dotnet nuget push "external-task-extension/bin/Release/external-task-extension.${{ steps.git_vars.outputs.SOURCE_TAG }}.nupkg" --api-key  ${{ secrets.PUBLISHER_PAT }} --source "https://nuget.pkg.github.com/asnapper/index.json"
